### ISSUE TITLE
java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/ser/std/ToStringSerializerBase

### ISSUE THREAD

**Issue by Phoenix616** [twitch4j/twitch4j#217]
### Prerequisites
* [ ] If this is a question/suggestion, I have already considered discuss it on [Discord Server](https://discord.gg/FQ5vgW3)
* [x] This issue specifically has something to do with Twitch4J
* [x] I have attempted to [look for similar issues](https://github.com/twitch4j/twitch4j/issues) already

### Description

When shading twitch4j 1.1.2 with maven it will not shade in the ToSTringSerializerBase and it is necessary

### Steps to Reproduce	
1. Add twitch4j to pom (e.g. [like this](https://github.com/MoepTv/discord-bot/blob/master/pom.xml#L57-L61))
2. Shade it in ([like this](https://github.com/MoepTv/discord-bot/blob/master/pom.xml#L78-L90))

---

**Expected behavior:** 

It to shade in all required dependency classes when shading in twitch4j.

**Actual behavior:** 

Missing classes resulting in the error.

**Stacktrace (if applicable):** 

```
Exception in thread "main" java.util.ServiceConfigurationError: com.fasterxml.jackson.databind.Module: com.fasterxml.jackson.datatype.jsr310.JavaTimeModule Unable to get public no-arg constructor
        at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:584)
        at java.base/java.util.ServiceLoader.getConstructor(ServiceLoader.java:675)
        at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1234)
        at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1266)
        at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1301)
        at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1386)
        at com.fasterxml.jackson.databind.ObjectMapper.findModules(ObjectMapper.java:982)
        at com.fasterxml.jackson.databind.ObjectMapper.findModules(ObjectMapper.java:966)
        at com.fasterxml.jackson.databind.ObjectMapper.findAndRegisterModules(ObjectMapper.java:1016)
        at com.github.twitch4j.helix.TwitchHelixBuilder.build(TwitchHelixBuilder.java:110)
        at com.github.twitch4j.TwitchClientBuilder.build(TwitchClientBuilder.java:316)
        at tv.moep.discord.bot.managers.StreamingManager.reload(StreamingManager.java:174)
        at tv.moep.discord.bot.MoepsBot.loadConfig(MoepsBot.java:175)
        at tv.moep.discord.bot.MoepsBot.<init>(MoepsBot.java:118)
        at tv.moep.discord.bot.MoepsBot.main(MoepsBot.java:104)
Caused by: java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/ser/std/ToStringSerializerBase
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:151)
        at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:821)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:719)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:642)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:600)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
        at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3215)
        at java.base/java.lang.Class.getConstructor0(Class.java:3420)
        at java.base/java.lang.Class.getConstructor(Class.java:2165)
        at java.base/java.util.ServiceLoader$1.run(ServiceLoader.java:662)
        at java.base/java.util.ServiceLoader$1.run(ServiceLoader.java:659)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:554)
        at java.base/java.util.ServiceLoader.getConstructor(ServiceLoader.java:670)
        ... 13 more
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.databind.ser.std.ToStringSerializerBase
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 30 more
```

**Version affected:** 
1.1.2, was fine with previously used 1.1.0

### Additional Information 

"Fixed" by manually shading in jackson-databind like this: https://github.com/MoepTv/discord-bot/commit/83ab24853d35e5fe95692b8a250d8901019ff1bd

**Comment by iProdigy** [comment]
Could you post the log output from when you did `mvn package` before explicitly adding databind to your pom?

**Comment by Phoenix616** [comment]
https://gist.github.com/Phoenix616/fc60def0bf62b204068892114994baa0

Looks like it somehow shades in an old version of Databind.

**Comment by iProdigy** [comment]
Thanks for sharing - as you identified, it's pulling 2.9.3 from Javacord: https://github.com/Javacord/Javacord/blob/eea300ba053a029b7f961d13a9c907b043a38f35/gradle/dependencies.gradle#L29

In the past we used to publish a fatJar (without any relocations), but don't anymore - sorry for the inconvenience

**Comment by Phoenix616** [comment]
Actually it's not just an issue in Javacord, it's one in twitch4j itself: An even older version seems to be used by archius-core -> feign-hystrix -> twitch4j-kraken

![](https://i.moep.tv/fNUYuXU3.png)

**Comment by iProdigy** [comment]
Since maven resolves versions via nearest-wins, the [old version used by archaius](https://github.com/Netflix/archaius/blob/master/build.gradle#L45) isn't pertinent. 

Speaking of which, you could try defining the twitch4j dependency before javacord in your pom and see if the correct jackson version is resolved.

**Comment by Phoenix616** [comment]
Yeah, that makes it use the correct version too. But of course that has the same downsides as directly specifying the version (potentially breaking the dependency of the other library :S) Guess there isn't really a good way around resolving this without actually updating the dependency in the other project or using different modules and relocating stuff.

Guess I'll close this issue seeing as we figured out the source and potential workarounds :) (I also opened an issue with Javacord regarding updating the dependency)
