### ISSUE TITLE
IllegalAccessError when closing client

### ISSUE THREAD

**Issue by GospelBG** [twitch4j/twitch4j#996]
### Prerequisites

- [X] If this is a question/suggestion, I have already considered discussing it on the [Discord Server](https://discord.gg/FQ5vgW3)
- [X] I have attempted to look for similar github issues already

### Expected Behavior

When I close the client, I get an IllegalAccessError from Hystrix.
When I call the .close() method I expect the Closing TwitchClient message and a successful action.

### Current Behavior

When I need to shutdown my program, i check if the client object is not null (has been initialized and used), and call the .close() method, altogether with other closing code for my program. 
```java
if (client != null) {
    client.close();
}
```  

When this "disable" method is called I get the first warning. When EventSub subscriptions have been used instead of that warning I get the second error below:

### Log output / Stacktrace

```txt
--- FIRST ERROR ---
[21:59:23 INFO]: [com.github.twitch4j.TwitchClient] Closing TwitchClient ...
[21:59:23 WARN]: [com.netflix.hystrix.AbstractCommand] Error calling HystrixCommandExecutionHook.onRunError
java.lang.IllegalAccessError: failed to access class com.netflix.hystrix.AbstractCommand$19 from class com.netflix.hystrix.AbstractCommand (com.netflix.hystrix.AbstractCommand$19 is in unnamed module of loader java.net.URLClassLoader @2b62c644; com.netflix.hystrix.AbstractCommand is in unnamed module of loader 'chatpointsttv-2.0.jar' @c90a9f7)
        at com.netflix.hystrix.AbstractCommand.getFallbackOrThrowException(AbstractCommand.java:781) ~[chatpointsttv-2.0.jar:?]
        at com.netflix.hystrix.AbstractCommand.handleFailureViaFallback(AbstractCommand.java:1034) ~[chatpointsttv-2.0.jar:?]
        at com.netflix.hystrix.AbstractCommand.access$700(AbstractCommand.java:60) ~[chatpointsttv-2.0.jar:?]
        at com.netflix.hystrix.AbstractCommand$12.call(AbstractCommand.java:621) ~[chatpointsttv-2.0.jar:?]
        at com.netflix.hystrix.AbstractCommand$12.call(AbstractCommand.java:601) ~[chatpointsttv-2.0.jar:?]
        at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onError(OperatorOnErrorResumeNextViaFunction.java:140) ~[chatpointsttv-2.0.jar:?]
        at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87) ~[chatpointsttv-2.0.jar:?]
        at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87) ~[chatpointsttv-2.0.jar:?]
        at com.netflix.hystrix.AbstractCommand$HystrixObservableTimeoutOperator$3.onError(AbstractCommand.java:1194) ~[chatpointsttv-2.0.jar:?]
        at rx.internal.operators.OperatorSubscribeOn$1$1.onError(OperatorSubscribeOn.java:59) ~[chatpointsttv-2.0.jar:?]
        at rx.observers.Subscribers$5.onError(Subscribers.java:230) ~[chatpointsttv-2.0.jar:?]
        at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87) ~[chatpointsttv-2.0.jar:?]
        at rx.observers.Subscribers$5.onError(Subscribers.java:230) ~[chatpointsttv-2.0.jar:?]
        at com.netflix.hystrix.AbstractCommand$DeprecatedOnRunHookApplication$1.onError(AbstractCommand.java:1431) ~[chatpointsttv-2.0.jar:?]
        at com.netflix.hystrix.AbstractCommand$ExecutionHookApplication$1.onError(AbstractCommand.java:1362) ~[chatpointsttv-2.0.jar:?]
        at rx.observers.Subscribers$5.onError(Subscribers.java:230) ~[chatpointsttv-2.0.jar:?]
        at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:216) ~[chatpointsttv-2.0.jar:?]
        at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:48) ~[chatpointsttv-2.0.jar:?]
        at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35) ~[chatpointsttv-2.0.jar:?]
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) ~[chatpointsttv-2.0.jar:?]
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) ~[chatpointsttv-2.0.jar:?]
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) ~[chatpointsttv-2.0.jar:?]
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) ~[chatpointsttv-2.0.jar:?]
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) ~[chatpointsttv-2.0.jar:?]
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) ~[chatpointsttv-2.0.jar:?]
        at rx.Observable.unsafeSubscribe(Observable.java:10151) ~[chatpointsttv-2.0.jar:?]
        at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:51) ~[chatpointsttv-2.0.jar:?]
        at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35) ~[chatpointsttv-2.0.jar:?]
        at rx.Observable.unsafeSubscribe(Observable.java:10151) ~[chatpointsttv-2.0.jar:?]
        at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41) ~[chatpointsttv-2.0.jar:?]
        at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30) ~[chatpointsttv-2.0.jar:?]
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) ~[chatpointsttv-2.0.jar:?]
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) ~[chatpointsttv-2.0.jar:?]
        at rx.Observable.unsafeSubscribe(Observable.java:10151) ~[chatpointsttv-2.0.jar:?]
        at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94) ~[chatpointsttv-2.0.jar:?]
        at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:56) ~[chatpointsttv-2.0.jar:?]
        at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:47) ~[chatpointsttv-2.0.jar:?]
        at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction.call(HystrixContexSchedulerAction.java:69) ~[chatpointsttv-2.0.jar:?]
        at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55) ~[chatpointsttv-2.0.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

--- SECOND ERROR ---
[22:36:34 INFO]: [com.github.twitch4j.TwitchClient] Closing TwitchClient ...
[22:36:36 WARN]: [com.github.twitch4j.client.websocket.WebsocketConnection] Underlying websocket did not close within the expected delay
[22:36:36 ERROR]: Error occurred while disabling ChatPointsTTV v2.0
java.lang.IllegalAccessError: failed to access class com.github.twitch4j.client.websocket.WebsocketConnection$2 from class com.github.twitch4j.client.websocket.WebsocketConnection (com.github.twitch4j.client.websocket.WebsocketConnection$2 is in unnamed module of loader java.net.URLClassLoader @5b22b05e; com.github.twitch4j.client.websocket.WebsocketConnection is in unnamed module of loader 'chatpointsttv-2.0.jar' @34fbf225)
        at com.github.twitch4j.client.websocket.WebsocketConnection.closeSocket(WebsocketConnection.java:365) ~[chatpointsttv-2.0.jar:?]
        at com.github.twitch4j.client.websocket.WebsocketConnection.disconnect(WebsocketConnection.java:279) ~[chatpointsttv-2.0.jar:?]
        at com.github.twitch4j.client.websocket.WebsocketConnection.close(WebsocketConnection.java:336) ~[chatpointsttv-2.0.jar:?]
        at com.github.twitch4j.chat.TwitchChat.close(TwitchChat.java:865) ~[chatpointsttv-2.0.jar:?]
        at com.github.twitch4j.ITwitchClient.close(ITwitchClient.java:113) ~[chatpointsttv-2.0.jar:?]
        at com.github.twitch4j.TwitchClient.close(TwitchClient.java:248) ~[chatpointsttv-2.0.jar:?]
        at me.gosdev.chatpointsttv.ChatPointsTTV.onDisable(ChatPointsTTV.java:210) ~[chatpointsttv-2.0.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:290) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:223) ~[paper-1.20.4.jar:git-Paper-497]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugins(PaperPluginInstanceManager.java:147) ~[paper-1.20.4.jar:git-Paper-497]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.clearPlugins(PaperPluginInstanceManager.java:153) ~[paper-1.20.4.jar:git-Paper-497]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.clearPlugins(PaperPluginManagerImpl.java:97) ~[paper-1.20.4.jar:git-Paper-497]
        at org.bukkit.plugin.SimplePluginManager.clearPlugins(SimplePluginManager.java:594) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.reload(CraftServer.java:1075) ~[paper-1.20.4.jar:git-Paper-497]
        at org.bukkit.Bukkit.reload(Bukkit.java:1024) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:54) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:999) ~[paper-1.20.4.jar:git-Paper-497]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchServerCommand(CraftServer.java:984) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:501) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:448) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1525) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-497]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Environment

- **Library Version**: 1.20.0
- **IDE**: VSCode
- **Java Version**: 17.0.8
- **Build Tools**: Maven 3.9.5
- **Operating System**: Windows 11

**Comment by iProdigy** [comment]
Unable to replicate on Paper 1.20.6 Build #148

Please create a minimal plugin jar that can reproduce this issue on a fresh paper server without any other plugins if you would like us to investigate
